### ISSUE TITLE
Failing to send a transaction on GanacheProvider

### ISSUE THREAD

**Issue by yivlad** [ethers-io/ext-provider-ganache#3]
Consider the following code:

```ts
import { Wallet, ZeroAddress, parseEther } from 'ethers';
import { GanacheProvider } from "@ethers-ext/provider-ganache";

(async () => {
  const wallet = Wallet.createRandom();
  const provider = new GanacheProvider();
  await provider.setAccount(wallet.address, {
    balance: '0x' + (10 ** 18).toString(16),
  })
  const signer = wallet.connect(provider);
  const tx = await signer.populateTransaction({
    value: parseEther('0.01'),
    to: ZeroAddress,
  });
  await (await signer.sendTransaction(tx)).wait();
})();
```

This fails with an error:
```sh
webpack://Ganache/../../chains/ethereum/transaction/lib/src/eip1559-fee-market-transaction.js:39
                    throw new ethereum_utils_1.CodedError(`Invalid chain id (${this.chainId.toNumber()}) for chain with id ${common.chainId()}.`, utils_1.JsonRpcErrorCode.INVALID_INPUT);
                          ^
CodedError: Invalid chain id (13370) for chain with id 1337.
    at new EIP1559FeeMarketTransaction (webpack://Ganache/../../chains/ethereum/transaction/lib/src/eip1559-fee-market-transaction.js:39:27)
    at Function.fromTxData (webpack://Ganache/../../chains/ethereum/transaction/lib/src/eip1559-fee-market-transaction.js:90:16)
    at Function._fromUnsafeUserData (webpack://Ganache/../../chains/ethereum/transaction/lib/src/transaction-factory.js:82:89)
    at Function.fromString (webpack://Ganache/../../chains/ethereum/transaction/lib/src/transaction-factory.js:199:23)
    at EthereumApi.apply (webpack://Ganache/../../chains/ethereum/ethereum/lib/src/api.js:1717:62)
    at EthereumApi.apply (webpack://Ganache/../../chains/ethereum/ethereum/lib/src/helpers/assert-arg-length.js:14:28)
    at Object.execute (webpack://Ganache/../utils/lib/src/utils/request-coordinator.js:80:47)
    at RequestCoordinator.call (webpack://Ganache/../utils/lib/src/utils/request-coordinator.js:59:22)
    at webpack://Ganache/../utils/lib/src/utils/request-coordinator.js:89:80
    at new Promise (<anonymous>) {
  code: -32000
}
```

**Comment by ricmoo** [comment]
Fixed in 6.0.0-beta.2, as well as exposing more underlying ganache features, so custom options may be passed in or a ganache instance can be passed in directly.

Thanks!
